### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'name'

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/elife-tools#67]
I've gotten 11 instances of this error out of all of our articles. `develop` branch.

The interesting bit is here:
```
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/elifetools/parseJATS.py", line 1669, in body
    body_content = render_raw_body(raw_body)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/elifetools/parseJATS.py", line 1681, in render_raw_body
    tag_content = body_block_content_render(boxed_tag)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/elifetools/parseJATS.py", line 1699, in body_block_content_render
    if body_block_content(child_tag) != {}:
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/elifetools/parseJATS.py", line 1721, in body_block_content
    if tag.name == "sec":
AttributeError: 'unicode' object has no attribute 'name'
```

but the full stacktrace is:

```
AttributeError: 'unicode' object has no attribute 'name'
Traceback (most recent call last):
  File "./src/main.py", line 280, in main
    article_json = render_single(doc)
  File "./src/main.py", line 270, in render_single
    return clean(render(description, [soup])[0])
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/et3/render.py", line 25, in render
    return map(lambda item: render_item(description, item), data)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/et3/render.py", line 25, in <lambda>
    return map(lambda item: render_item(description, item), data)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/et3/render.py", line 14, in render_item
    result[key] = render_item(sub_description, item)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/et3/render.py", line 16, in render_item
    result[key] = doall(item, pipeline)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/et3/render.py", line 6, in doall
    v = x(v) if callable(x) else x
  File "./src/main.py", line 163, in fn
    return actual_func(soup, *args, **kwargs)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/elifetools/parseJATS.py", line 1669, in body
    body_content = render_raw_body(raw_body)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/elifetools/parseJATS.py", line 1681, in render_raw_body
    tag_content = body_block_content_render(boxed_tag)
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/elifetools/parseJATS.py", line 1699, in body_block_content_render
    if body_block_content(child_tag) != {}:
  File "/home/luke/dev/python/bot-lax-adaptor/venv/lib/python2.7/site-packages/elifetools/parseJATS.py", line 1721, in body_block_content
    if tag.name == "sec":
AttributeError: 'unicode' object has no attribute 'name'
```

affected articles:

* elife-14345-v1
* elife-14311-v1
* elife-13977-v1
* elife-13367-v2
* elife-13093-v1
* elife-12852-v1
* elife-12760-v1
* elife-12724-v1
* elife-12721-v1
* elife-12481-v1
* elife-12260-v1

**Comment by gnott** [comment]
Thanks Luke. I ignored these parsing errors for a little bit.

I think I tracked it down to when there is whitespace between p tags. The function that renders sections of the body sends it for rendering, expecting it was a tag.

I have a fix for now and a test for it.

How this works in the future may change, though the existing tests should hopefully not let this happen again in this way.
